karmor recommend: handling policy-templates
kubearmor/kubearmor-client pull request #180
Opened 2022-09-13 20:47 UTC by vishnusomank

- Created sample metadata.yaml in [repo](https://github.com/vishnusomank/policy-templates/blob/main/MySQL/system/metadata.yaml)
- Created release of [policy-templates](https://github.com/vishnusomank/policy-templates/releases)
- Updated code with `karmor recommend --update`. This will download the latest policy-template release
- Updated code with check for whether latest policy-templates are available when using `karmor recommend`

Addresses https://github.com/kubearmor/kubearmor-client/issues/176

Signed-off-by: vishnusomank <vishnu@accuknox.com>

2022-09-13 20:50 UTC, vishnusomank commented
Hi, @nyrahul @wazir-ahmed I've raised a draft PR for `recommend: handling policy-templates` can you take a look at it and suggest if any changes or improvements are needed?
PR : [https://github.com/kubearmor/kubearmor-client/pull/180](https://github.com/kubearmor/kubearmor-client/pull/180)

2022-09-14 06:35 UTC, nyrahul requested changes
I think the important question for me from the PR is:

We are trying to create ~/.cache/karmor/rules.yaml in the user's home directory. Is that our intention? I dont think that is what we discussed!

My understanding was that `karmor update` would be used only by the developer to update the rules.yaml in the kubearmor-client repo. So after the update is done the rules.yaml would be updated and pushed to the repo as a PR.

CC: @wazir-ahmed WDYT?

2022-09-14 06:35 UTC, nyrahul commented on recommend/policyTeamplates.go
> +
use defer create.Close() here .. otherwise it leads to leak below in the case of error situation

2022-09-14 06:35 UTC, nyrahul commented on recommend/policyTeamplates.go
> +		open, err := file.Open()
open.Close() needs to be handled.

2022-09-14 06:35 UTC, nyrahul commented on recommend/policyTeamplates.go
> +
```suggestion
```

2022-09-14 06:35 UTC, nyrahul commented on recommend/policyTeamplates.go
> +
```suggestion
```

2022-09-17 10:21 UTC, closed without merging