bind port connections table for summarised data
kubearmor/kubearmor-client pull request #219
Opened 2022-12-06 09:38 UTC by yasin-cs-ko-ak

This PR Contains 
- Bind Port Network Connection details for summarised data. 
- This will show when kubearmor log data has "SYS_BIND" under it's network data.
This is how sample output will look like.
```

Bind Port Connections
+----------+---------------------------+-----------------------------+-----------+--------------+-----------+--------+-------+------------------------------+
| PROTOCOL |          COMMAND          |         POD/SVC/IP          | BIND PORT | BIND ADDRESS | NAMESPACE | LABELS | COUNT |      LAST UPDATED TIME       |
+----------+---------------------------+-----------------------------+-----------+--------------+-----------+--------+-------+------------------------------+
| UNIX     | /usr/sbin/mysqld          | /var/run/mysqld/mysqld.sock |           |              |           |        | 2     | Tue Dec  6 08:16:13 UTC 2022 |
|          | /usr/lib/apt/methods/http |                             |           |              |           |        | 3     | Tue Dec  6 08:18:29 UTC 2022 |
|          | /bin/nc.traditional       |                             |           |              |           |        | 2     | Tue Dec  6 08:54:54 UTC 2022 |
+----------+---------------------------+-----------------------------+-----------+--------------+-----------+--------+-------+------------------------------+
```
if SYS_BIND doesn't happen it will show empty.

2022-12-08 13:11 UTC, nyrahul approved these changes

2022-12-09 06:10 UTC, nyrahul requested changes

2022-12-09 06:10 UTC, nyrahul commented on summary/table.go
> +			fmt.Printf("\nBind Port connections\n")
```suggestion
			fmt.Printf("\nBind points\n")
```

2022-12-09 14:29 UTC, yasin-cs-ko-ak commented on summary/table.go
> +			fmt.Printf("\nBind Port connections\n")
Renamed the title.

2022-12-09 14:31 UTC, yasin-cs-ko-ak commented
The output:
```
Bind Points
+----------+------------------+-----------+--------------+-------+------------------------------+
| PROTOCOL |     COMMAND      | BIND PORT | BIND ADDRESS | COUNT |      LAST UPDATED TIME       |
+----------+------------------+-----------+--------------+-------+------------------------------+
| UNIX     | /usr/sbin/mysqld |           |              | 2     | Wed Dec  7 14:04:27 IST 2022 |
|          | /usr/sbin/mysqld | 3306      | ::           | 1     | Wed Dec  7 14:04:27 IST 2022 |
+----------+------------------+-----------+--------------+-------+------------------------------+
```

2022-12-15 06:13 UTC, seswarrajan approved these changes
LGTM

2022-12-15 23:21 UTC, nyrahul approved these changes

2022-12-15 23:22 UTC, merged