add verbose flag for karmor probe
kubearmor/kubearmor-client pull request #227
Opened 2023-01-01 17:27 UTC by kranurag7

Signed-off-by: Anurag <contact.anurag7@gmail.com>

- Refactored the output of `karmor probe`.
- The usual loading time is 1/3rd of the existing one. 
```bash
# truncated
$ time ./kubearmor-client probe 
./kubearmor-client probe  0.09s user 0.01s system 1% cpu 6.258 total
$ time ./kubearmor-client probe -v 
./kubearmor-client probe -v  0.16s user 0.05s system 1% cpu 18.309 total
```
- The new output looks something like this. 
```bash
$ ./kubearmor-client probe

Found KubeArmor running in Kubernetes

Daemonset :
 	kubearmor 	Desired: 3	Ready: 3	Available: 3	
Armored Up pods :
+-----------+------+--------+
| NAMESPACE | NAME | POLICY |
+-----------+------+--------+
| default   | pod  |        |
+-----------+------+--------+
```

2023-01-07 13:30 UTC, nyrahul requested changes

2023-01-07 13:30 UTC, nyrahul commented on probe/probe.go
> +// only annotated pods and corresponding policies
```suggestion
// PrintAnnotatedPods only annotated pods and corresponding policies
```

2023-01-07 13:30 UTC, nyrahul commented on cmd/probe.go
>  		return nil
```suggestion
		if !verbose {
			return probe.PrintAnnotatedPods(client, probeInstallOptions)
		}
		return probe.PrintProbeResult(client, probeInstallOptions); err != nil {
```

2023-01-27 09:57 UTC, yasin-cs-ko-ak commented
@kranurag7 Kindly review the suggested changes.
cc: @nyrahul

2023-10-18 08:55 UTC, kranurag7 commented
This proposal is not planned as of now (as per our discussion in community meetings). Closing this. `karmor probe` does the job.

2023-10-18 08:55 UTC, closed without merging