fix `karmor uninstall`
kubearmor/kubearmor-client pull request #382
Opened 2023-11-03 06:06 UTC by Ankurk99

**Description**
- Uninstall KubeArmor Daemonset
- Uninstall all the resources based on label (kubearmor-app)

2023-11-06 10:15 UTC, daemon1024 requested changes

2023-11-06 10:15 UTC, daemon1024 commented on install/install.go
> +	clusterRoleList, err := c.K8sClientset.RbacV1().ClusterRoles().List(context.TODO(), metav1.ListOptions{LabelSelector: "kubearmor-app"})
Is this backwards compatible?
We don't have the label selector in the current Cluster Role right?

2023-11-17 06:06 UTC, DelusionalOptimist commented on cmd/uninstall.go
> +	uninstallCmd.Flags().StringVarP(&uninstallOptions.Namespace, "namespace", "n", "", "Namespace for resources")
I think we should add to the help message what would the default behavior be when no namespace is specified? :thinking:

2023-11-17 11:47 UTC, daemon1024 requested changes
small nit, tried it out locally. Works as intended. LGTM 🙌🏽

2023-11-17 11:47 UTC, daemon1024 commented on install/install.go
> +}
Use https://pkg.go.dev/slices#Contains

2023-11-17 13:05 UTC, DelusionalOptimist commented on install/install.go
> +	"slices"
I think this package is still in experimental before Go 1.21.
Either need to update go.mod and CI workflows OR use `"golang.org/x/exp/slices"`

2023-11-17 13:31 UTC, DelusionalOptimist approved these changes
LGTM! Thanks @Ankurk99. :rocket:

2023-11-17 13:35 UTC, daemon1024 approved these changes

2023-11-17 13:41 UTC, merged