Changed the description for long description for `install` command
kubearmor/kubearmor-client pull request #384
Opened 2023-11-10 14:19 UTC by HARI-124

This PR solves the issue #376 by adding a long description for install command.

2023-11-28 10:58 UTC, daemon1024 requested changes

2023-11-28 10:58 UTC, daemon1024 commented on cmd/install.go
> +	Long: `Safeguard your Kubernetes cluster effortlessly with KubeArmor CLI installation. This streamlined process equips your
The goal of long description is to explain about how KubeArmor autodetects environment and installs things accordingly.

As well explain different ways to use it
karmor install --save
karmor install --env=<specify env>
or passing namespace.

Let's keep the description as functional as possible.

2023-12-11 05:48 UTC, HARI-124 commented
@daemon1024 I am closing this pr and I'll create a new pr with the correct commit signing sorry I forgot to sign the commit

2023-12-11 05:54 UTC, HARI-124 commented
I am closing this and creating a new pr i did  some problems in my local repo

2023-12-11 05:54 UTC, closed without merging