feat: (recommend) Implement recommend functionality for Docker Client
kubearmor/kubearmor-client pull request #461
Opened 2024-09-17 10:34 UTC by tesla59

Instead of passing K8s client directly to recommend.Recommend(), use an interface to pass K8s Client. This way we can pass both K8s Client and Docker Client

2024-10-02 11:57 UTC, tesla59 commented
@daemon1024 please review

2024-10-03 06:32 UTC, daemon1024 commented
Can you include screenshots of how it's working?

2024-10-03 06:54 UTC, tesla59 commented
Case 1: systemd mode
![image](https://github.com/user-attachments/assets/b01ec5ea-47a0-43fa-b520-b544328d2c2d)

- `karmor recommend` fails due to --k8s=true by default and no cluster is running. K8s client is used
- `karmor recommend --k8s=false` uses docker client but policy is not generated due to no containers running
- `karmor recommend --k8s=false` generates policy after nginx container is run and policy is generated

![image](https://github.com/user-attachments/assets/bd141ecf-9503-4577-98fa-e1f1f7baf3da)

Case 2: k8s mode
<img width="587" alt="image" src="https://github.com/user-attachments/assets/e35f64bc-506b-4545-aba1-19aa1a833d07">
Works as before

There is an error `ERRO[0010] Not a valid tar file                          file=/tmp/karmor867115595/blobs/sha256/0162fa012a5d588eb52b8edaef90c4aecf89021924a20a2ca62f8dad7b766bf7` but it is not related to this PR. Will push fix for that in another pr

2024-11-11 15:53 UTC, rootxrishabh reviewed
Initial review - Changes are working as expected.
![Screenshot from 2024-11-11 20-49-43](https://github.com/user-attachments/assets/f3a92b65-0157-40cd-94ae-79076d9564a0)

2024-11-11 15:54 UTC, rootxrishabh commented
Output directory is `-server-1` which gives an error if I try to enter it - 
`
rootxrishabh@fedora:/tmp/out$ cd -server-1
bash: cd: -s: invalid option
cd: usage: cd [-L|[-P [-e]] [-@]] [dir]
`

2024-11-13 10:32 UTC, tesla59 commented
> cd -server-1

shouldn't this be `cd -- -server-1`

ill check what is the issue with output directory name

2024-11-19 05:37 UTC, tesla59 commented
@rootxrishabh policy directory is fixed. it was due to `img.namespace` being null in VM mode.
<img width="956" alt="image" src="https://github.com/user-attachments/assets/940b8886-a883-47f9-a60f-4dd603410e46">

2024-11-19 05:44 UTC, tesla59 commented
@rootxrishabh also added commit to trim new line character in final report generation. it fixes the weird number of blank lines after reports table
<img width="1235" alt="image" src="https://github.com/user-attachments/assets/f1f90fe1-ec55-42ee-a029-081ee849daa9">
Old
<img width="1248" alt="image" src="https://github.com/user-attachments/assets/74d30198-90c8-48c5-aecc-b1bcfc4c65cb">
New

2025-01-02 11:12 UTC, rootxrishabh requested changes
karmor crashes when using `--k8s` and `-i` together. @tesla59 PTAL
![image](https://github.com/user-attachments/assets/ef36c2b8-3241-4b3a-9a42-a294f98325fd)

2025-01-02 11:16 UTC, rootxrishabh commented
karmor exists with an error. With `-k8s=false` and an nginx container running on docker. Is this intended?
```yaml
accuknox/kubearmor-client - (tesla/non-k8s/karmor-recommend) > docker ps
CONTAINER ID   IMAGE     COMMAND                  CREATED          STATUS          PORTS     NAMES
45eb1cf51480   nginx     "/docker-entrypoint.…"   20 minutes ago   Up 20 minutes   80/tcp    modest_pascal

accuknox/kubearmor-client - (tesla/non-k8s/karmor-recommend) > ./karmor recommend -k=false
ERRO[0000] no Object found to secure, hence nothing to recommend!  namespace=
```

2025-01-11 11:37 UTC, tesla59 commented
hey @rootxrishabh 
i am unable to reproduce any of the above issues

When running `karmor recommend --k8s=false -i nginx`
<img width="1635" alt="image" src="https://github.com/user-attachments/assets/c17ed948-97b6-4536-a194-6801eb91e934" />

When running `karmor recommend -k=false` with nginx running as docker container
<img width="1632" alt="image" src="https://github.com/user-attachments/assets/a1bc3edd-c6f3-4ca4-97a2-8b5c067e2a78" />

I think the issue could be due to different envs, although unlikely. 
Another thing that i noticed was i missed one error check when listing objects in Recommend() function, which is where the 2nd screenshot is not working as expected. i have pushed the fix for error check can u please check again? i believe there is some error while listing the object which is why its throwing array index out of range. ill push another debug branch which has bunch of log.Info(), it will give more insights on where the panic is actually happening (since in the original screenshot, it is not possible to judge anything)

link to [debug branch](https://github.com/tesla59/kubearmor-client/tree/tesla/non-k8s/karmor-recommend-debug)

2025-01-15 18:08 UTC, rootxrishabh reviewed
Tested `karmor recommend --k8s=false -i nginx` seems to work now - 
```yaml
accuknox/kubearmor-client - (tesla/non-k8s/karmor-recommend) > ./karmor recommend --k8s=false -i nginx
INFO[0000] Found outdated version of policy-templates    Current Version=v0.2.3
INFO[0000] Downloading latest version [v0.2.6]
INFO[0001] policy-templates updated                      Updated Version=v0.2.6
INFO[0001] pulling image                                 image=nginx
latest: Pulling from library/nginx
7ce705000c39: Pull complete
b3e9225c8fca: Pull complete
2b39a3d0829e: Pull complete
6d24e34787c7: Pull complete
066d623ff8e6: Pull complete
49486a4a61a6: Pull complete
34d83bb3522a: Pull complete
Digest: sha256:0a399eb16751829e1af26fea27b20c3ec28d7ab1fb72182879dcae1cca21206a
Status: Downloaded newer image for nginx:latest
INFO[0063] dumped image to tar                           tar=/var/folders/xp/hyg6_b6j7hgc23b7bd7d35l00000gn/T/karmor2062359421/pakTcFqD.tar
Distribution debian
created policy out/nginx-latest/write-under-dev-dir.yaml ...
created policy out/nginx-latest/k8s-client-tool-exec.yaml ...
created policy out/nginx-latest/file-system-mounts.yaml ...
created policy out/nginx-latest/crypto-miners.yaml ...
created policy out/nginx-latest/cis-commandline-warning-banner.yaml ...
created policy out/nginx-latest/file-integrity-monitoring.yaml ...
created policy out/nginx-latest/cronjob-cfg.yaml ...
created policy out/nginx-latest/pkg-mngr-exec.yaml ...
created policy out/nginx-latest/remote-file-copy.yaml ...
created policy out/nginx-latest/write-etc-dir.yaml ...
created policy out/nginx-latest/impair-defense.yaml ...
created policy out/nginx-latest/user-grp-mod.yaml ...
created policy out/nginx-latest/maint-tools-access.yaml ...
created policy out/nginx-latest/write-in-shm-dir.yaml ...
created policy out/nginx-latest/access-ctrl-permission-mod.yaml ...
created policy out/nginx-latest/remote-services.yaml ...
created policy out/nginx-latest/trusted-cert-mod.yaml ...
created policy out/nginx-latest/system-owner-discovery.yaml ...
created policy out/nginx-latest/system-network-env-mod.yaml ...
created policy out/nginx-latest/network-service-scanning.yaml ...
output report in out/report.txt ...
  Container               | nginx:latest
  OS                      | linux
  Arch                    | arm64
  Distro                  | debian
  Output Directory        | out/nginx-latest
  policy-template version | v0.2.3
+-------------------------------------+--------------------------------+----------+--------+---------------------------------------------------+
|               POLICY                |           SHORT DESC           | SEVERITY | ACTION |                       TAGS                        |
+-------------------------------------+--------------------------------+----------+--------+---------------------------------------------------+
| write-under-dev-dir.yaml            | Audit device directory for     | 5        | Audit  | NIST NIST_800-53_AU-2                             |
|                                     | enhanced security              |          |        | NIST_800-53_SI-4 MITRE                            |
|                                     |                                |          |        | MITRE_T1036_masquerading                          |
+-------------------------------------+--------------------------------+----------+--------+---------------------------------------------------+
| k8s-client-tool-exec.yaml           | Prevent execution of container | 5        | Block  | MITRE_T1609_container_administration_command      |
|                                     | administration tools within a  |          |        | MITRE_TA0002_execution                            |
|                                     | container                      |          |        | MITRE_T1610_deploy_container                      |
|                                     |                                |          |        | MITRE NIST_800-53 NIST_800-53_AU-2                |
|                                     |                                |          |        | NIST_800-53_SI-4 NIST                             |
+-------------------------------------+--------------------------------+----------+--------+---------------------------------------------------+
| file-system-mounts.yaml             | Ensure successful file system  | 5        | Audit  | CIS CIS_Linux                                     |
|                                     | mounts are collected           |          |        | CIS_4_Logging_and_Aduditing                       |
|                                     |                                |          |        | CIS_4.1.1_Data_Retention                          |
|                                     |                                |          |        | CIS_4.1.14_file_system_mount                      |
+-------------------------------------+--------------------------------+----------+--------+---------------------------------------------------+
| crypto-miners.yaml                  | Cryptojacking, Crypto mining,  | 10       | Block  | cryptominer                                       |
|                                     | Malware protection             |          |        | MITRE_T1496_resource_hijacking                    |
|                                     |                                |          |        | MITRE                                             |
+-------------------------------------+--------------------------------+----------+--------+---------------------------------------------------+
| cis-commandline-warning-banner.yaml | Command Line Warning Banners   | 5        | Block  | CIS CIS_Linux CIS_1.7_Warning_Banners             |
|                                     |                                |          |        | CIS_1.7.1_Command_Line_Warning_Banners            |
+-------------------------------------+--------------------------------+----------+--------+---------------------------------------------------+
| file-integrity-monitoring.yaml      | File Integrity                 | 1        | Block  | NIST NIST_800-53_AU-2                             |
|                                     | Monitoring/Protection          |          |        | NIST_800-53_SI-4 MITRE                            |
|                                     |                                |          |        | MITRE_T1036_masquerading                          |
|                                     |                                |          |        | MITRE_T1565_data_manipulation                     |
+-------------------------------------+--------------------------------+----------+--------+---------------------------------------------------+
| cronjob-cfg.yaml                    | Audit access to cronjob files  | 5        | Audit  | NIST SI-4                                         |
|                                     | as a part of system monitoring |          |        | NIST_800-53_SI-4                                  |
|                                     | for better integrity           |          |        | CIS CIS_Linux                                     |
|                                     |                                |          |        | CIS_5.1_Configure_Cron                            |
+-------------------------------------+--------------------------------+----------+--------+---------------------------------------------------+
| pkg-mngr-exec.yaml                  | Prohibit package manager       | 5        | Block  | NIST                                              |
|                                     | process execution in           |          |        | NIST_800-53_CM-7(4)                               |
|                                     | containers to maintain system  |          |        | SI-4 process                                      |
|                                     | integrity and [...]

2025-01-15 18:23 UTC, rootxrishabh requested changes
But the docker client is throwing an error for being newer than the daemon. Please think of a way to handle this as most users could face this issue. I see we are using `github.com/docker/docker v25.0.5+incompatible`. @daemon1024 any ideas?
```yaml
accuknox/kubearmor-client - (tesla/non-k8s/karmor-recommend) > ./karmor recommend --k8s=false
Error: Error response from daemon: client version 1.44 is too new. Maximum supported API version is 1.43
```

2025-01-19 06:36 UTC, tesla59 commented
hey @rootxrishabh can u share the output of `docker version`
as per the docker sdk documentation, API versions before v24 are deprecated

`github.com/docker/docker@v24.0.9+incompatible` gives while trying to compile
```
../../../../go/pkg/mod/oras.land/oras-go@v1.2.4/pkg/auth/docker/login_tls.go:44:20: undefined: types.AuthConfig
../../../../go/pkg/mod/oras.land/oras-go@v1.2.4/pkg/auth/docker/login_tls.go:62:131: undefined: types.AuthConfig
../../../../go/pkg/mod/oras.land/oras-go@v1.2.4/pkg/auth/docker/login_tls.go:122:32: undefined: types.AuthConfig
../../../../go/pkg/mod/oras.land/oras-go@v1.2.4/pkg/auth/docker/login.go:54:16: undefined: types.AuthConfig
```

`github.com/docker/docker@v25.0.7+incompatible` gives while trying to compile
```
recommend/registry/registry.go:174:16: undefined: dockerTypes.PullOptions
```

`github.com/docker/docker@v26.1.5+incompatible` seem to work just fine

I think that begs the question how many Daemon version do we intend to support and which version should we use

2025-01-19 06:38 UTC, tesla59 commented
although the v27 docker client was already present in the `go.mod` in kubearmor-client
https://github.com/kubearmor/kubearmor-client/blob/325762c67aa8e01e0627c5413100c90f2148fe0b/go.mod#L14C2-L14C47

2025-01-29 18:14 UTC, rootxrishabh reviewed
My docker version is `24.0.2`. So it should be supported?

2025-02-24 09:27 UTC, rootxrishabh commented
@tesla59, can we use [github.com/docker/docker/clientv28](https://pkg.go.dev/github.com/docker/docker@v28.0.0+incompatible/client)? Let's check if it supports at least 3 versions below it.

2025-07-15 07:59 UTC, rksharma95 commented
tested locally working as expected.
<img width="1506" height="749" alt="Screenshot From 2025-07-15 13-26-48" src="https://github.com/user-attachments/assets/b0c555c0-1680-4b30-8a3a-8b12478b0b85" />

2025-07-15 07:59 UTC, rksharma95 approved these changes

2025-07-15 08:00 UTC, rksharma95 commented
@tesla59 please rebase the main and squash the commits.

2025-07-15 16:00 UTC, tesla59 commented
@rksharma95 rebased to main and squashed the commits

2025-07-15 17:37 UTC, rootxrishabh approved these changes

2025-07-22 03:55 UTC, rootxrishabh approved these changes

2025-07-22 04:09 UTC, Aryan-sharma11 approved these changes

2025-07-22 04:09 UTC, merged