Refactor telemetry helpers
kubearmor/kubearmor-client pull request #96
Opened 2022-07-05 18:08 UTC by daemon1024

- handle alert and logs in same helper
- future proof output for telemetry events fields

2022-07-05 19:10 UTC, daemon1024 commented
Ended up going back the way we handled eventChannel initally in https://github.com/kubearmor/kubearmor-client/pull/94 😅

2022-07-06 03:52 UTC, nyrahul requested changes
Thanks for taking this up. Few comments inline.

2022-07-06 03:52 UTC, nyrahul commented on log/log.go
> +// StopObserver unblocks signal
Thanks. Looks like I forgot to add this.

2022-07-06 03:52 UTC, nyrahul commented on log/logClient.go
> +			"Source",
There is field called `Message` which needs to be shown up after Severity.

2022-07-06 03:52 UTC, nyrahul commented on log/logClient_test.go
> +		t.Errorf(err.Error())
Errorf and return.

2022-07-06 03:52 UTC, nyrahul commented on log/logClient_test.go
> +	case <-time.After(100 * time.Millisecond):
Thanks for doing this properly.

2022-07-06 03:52 UTC, nyrahul commented on log/logClient_test.go
> +	go waitOnAlert(maxEvents)
we can remove `waitOnAlert()` and this code section ... doesn't serve any new purpose since there is `waitOnGenericEvent()` now.

2022-07-08 00:59 UTC, nyrahul approved these changes
LGTM

2022-07-08 00:59 UTC, merged