fixed sysdump crash bug
kubearmor/kubearmor-client pull request #99
Opened 2022-07-09 19:14 UTC by AvineshTripathi

fixes #88

2022-07-12 07:25 UTC, daemon1024 requested changes
Thanks a lot for the PR 🚀 

Can you share a sample `sysdump` if KubeArmor is not running?

Some comments inline, We used to use "kube-system" but KubeArmor can run in other namespaces as well, let's make the function Namespace agnostic if possible.

Also, there are some linter warning, Can you check if they can be handle!

Thanks again 😁

2022-07-12 07:25 UTC, daemon1024 commented on sysdump/sysdump.go
> +	pods, err := c.K8sClientset.CoreV1().Pods("kube-system").List(context.Background(), metav1.ListOptions{
```suggestion
	pods, err := c.K8sClientset.CoreV1().Pods("").List(context.Background(), metav1.ListOptions{
```

Let's check in all namespaces.

2022-07-12 07:25 UTC, daemon1024 commented on sysdump/sysdump.go
> +		fmt.Println("Kube-armor is not running in your cluster")
```suggestion
		fmt.Println("KubeArmor is not running in your cluster")
```

2022-07-14 06:24 UTC, AvineshTripathi commented
Hey! i think with the new merge of #102 when I do `make install` I see following error which should be resolved 
![2022-07-14_11-51](https://user-images.githubusercontent.com/73980067/178914375-0db03590-c102-45c5-bb99-27739b6d869e.png)

Also if i remove the PR then following output is shown when kubearmor is not running 
![2022-07-14_11-35](https://user-images.githubusercontent.com/73980067/178914544-8fdc677a-843e-4d0e-aa78-6ae2c0dc233f.png)

2022-07-15 03:28 UTC, nyrahul commented
> Hey! i think with the new merge of #102 when I do `make install` I see following error which should be resolved ![2022-07-14_11-51](https://user-images.githubusercontent.com/73980067/178914375-0db03590-c102-45c5-bb99-27739b6d869e.png)
> 
> Also if i remove the PR then following output is shown when kubearmor is not running ![2022-07-14_11-35](https://user-images.githubusercontent.com/73980067/178914544-8fdc677a-843e-4d0e-aa78-6ae2c0dc233f.png)

Hey @AvineshTripathi , I do not face this issue when `make install` is attempted. Do you want to get on kubearmor slack and check?

2022-07-15 11:57 UTC, AvineshTripathi commented
@nyrahul with the latest merge the current PRs commit is throwing error

2022-07-15 13:44 UTC, daemon1024 commented
I am guessing something went wrong resolving merge conflicts? Yup let's take it to slack #development if you are still facing issues,

2022-08-23 05:34 UTC, daemon1024 commented
Hey @AvineshTripathi, Were you able to sort out the build failures. Anything I can help out with?

2022-09-12 18:56 UTC, nyrahul commented
Hey @AvineshTripathi , it would be great to get this handled. Please ping on slack if any discussion needed. Please fix the conflicts, rebase and mostly we should be good to go.

2022-09-17 03:21 UTC, AvineshTripathi commented
Hey sorrry for delaying with this PR will be solving the conflicts in some hours

2022-09-17 04:06 UTC, AvineshTripathi commented
Closing this PR and creating a fresh PR with resolved conflicts

2022-09-17 04:06 UTC, closed without merging